### ISSUE TITLE
Build User Variables plugin should use EnvInject

### ISSUE THREAD

**Issue by sodabrew** [jenkinsci/envinject-plugin#10]
The [Build User Vars](https://wiki.jenkins-ci.org/display/JENKINS/Build+User+Vars+Plugin) plugin does not support Matrix builds. It would if it used EnvInject. Since you've commented on that plugins page, and that plugins repo does not have an issue tracker, I'm opening here... to please submit a patch to the build user vars plugin that has it using EnvInject to support its parameters into the full build process.

**Comment by oleg-nenashev** [comment]
This case should work correctly in build-user-vars-plugin-1.4
