### ISSUE TITLE
Weird Environment Variable

### ISSUE THREAD

**Issue by TASSDevon** [jenkinsci/envinject-plugin#110]
Hi,

Since the last 2 or so updates of this plugin I noticed there is an odd env variable when I check the list in a Jenkins job.

It's =:: with value ::\

The name used to be without the equal symbol in front (it has been like this for a long time now that I checked and went back weeks/months).

Now, I'm not sure if this is caused by the plugin or not but it seems plausible. The reason this pops up now is because the Coverity plugin is complaining about a malformed env variable "java.lang.RuntimeException: Array of environment variables contains a malformed element: =::=::\"

Any ideas how this can be resolved, could this be a bug in the plugin? Let me know if I can send you some logging to get to the bottom of this.

Cheers,
Devon

**Comment by oleg-nenashev** [comment]
Please create a Jenkins JIRA ticket and attach your EnvInject configuration there. The plugin itself is not supposed to inject such variables.
