### ISSUE TITLE
Job configuration reverted after build start

### ISSUE THREAD

**Issue by domdom82** [jenkinsci/envinject-plugin#111]
I am trying to configure my job to inject env vars before running a pipeline job.

**Jenkins 2.7.2**
**Envinject 1.92.1**

1. Create pipeline job
2. Select "Prepare an environment for the run"
3. Set variables in "Properties Content"
4. Click "save"
5. Run build

**Expected behavior:**

Job configuration is saved and used every time.

**Observed behavior:**

Job configuration is reverted by SYSTEM user and used only for this job run.
Subsequent jobs will not have environment vars injected.

**Comment by oleg-nenashev** [comment]
EnvInject plugin does not support Pipeline plugin.
If you need to get such support, please find/create an issue in Jenkins JIRA
