### ISSUE TITLE
Properties file path not evaluated after SCM checkout

### ISSUE THREAD

**Issue by xait-arne-trodahl** [jenkinsci/envinject-plugin#112]
The help text for the properties file path field states that the file will be evaluated after an SCM checkout. If I create a new project with an empty workspace and set it up to check out a git repo which contains the properties file, the build will fail before the SCM checkout stating that the properties file cannot be found. Thus either the help text for the field is wrong, or the plugin implementation.

The project type is a multi configuration job and the plugin version is 1.93.1.
<img width="968" alt="screen shot 2017-01-13 at 10 37 43 am" src="https://cloud.githubusercontent.com/assets/6310292/21925357/68430182-d97d-11e6-83b8-83119dc7e18f.png">

**Comment by phulst** [comment]
I'm seeing a similar issue, but for me Script File Path that is not being evoked pre-build. The Script Content is also not evaluated for me.  (I haven't actually tried the Properties File Path) 

I wonder if this plugin is broken for later versions of Jenkins. I'm also using 1.93.1 with Jenkins version 2.32.3

**Comment by oleg-nenashev** [comment]
Created https://issues.jenkins-ci.org/browse/JENKINS-43864. Closing this issue since I am going to finally close this unofficial tracker
