### ISSUE TITLE
EnvInject: edits to Groovy script not saved when Job modified

### ISSUE THREAD

**Issue by edrandall** [jenkinsci/envinject-plugin#113]
1. Set up a Jenkins job;
Under (General) "Prepare an environment for the run" enter some script in the "Evaluated Groovy script" box
Finish configuring your job and save;  The groovy script will be saved fine with the job.
2. Edit the job;  Modify the "Evaluated Groovy script";  Save;
3. Edit the job again;  The "Evaluated Groovy script" changes made in (2) will not have been saved.
4. (Workaround) Edit the job again; Un-tick "Prepare an environment for the run"; Save;  Edit again; Tick "Prepare an environment for the run" and enter the modified script in "Evaluated Groovy Script".

**Comment by oleg-nenashev** [comment]
Please retry with EnvInject 2.0. The script management logic has been reworked there. If the issue still happens, please create a bug in Jenkins JIRA
