### ISSUE TITLE
EnvInject seems not called when running Pipeline script from SCM

### ISSUE THREAD

**Issue by christophe-henry-devoteam** [jenkinsci/envinject-plugin#114]
How to reproduce:

1. create a new Pipeline job,
2. select `Pipeline script from SCM` in pipeline definition,
3. fill input `Branches to build` with `origin/${branch}`
4. select `Prepare environment for the run` and fill `Evaluated Groovy script` with:

```
if (!binding.variables.containsKey("branch")) {
    return [branch: "master"]
}
```

The build is expected to checkout the repo on branch `master` but the `branch` variable is not initialized. The log will display

```git rev-parse refs/remotes/origin/origin/${branch}^{commit} # timeout=10```

I'm not sure whether this bug comes from the EnvInject plugin or from Pipeline.

**Comment by oleg-nenashev** [comment]
EnvInject is not integrated with Pipeline.
Any integration use-cases may fail.

Please raise an issue in the JIRA bugtracker

**Comment by christophe-henry-devoteam** [comment]
Oh, right. Well it seems [there's alrady one](https://issues.jenkins-ci.org/browse/JENKINS-38483). Do you think it's a complex task? Maybe it's something I can contribute to?

**Comment by oleg-nenashev** [comment]
Hard to say. Pipeline does not implement all Jenkins extension points, so it maybe either easy or impossible. Maybe @jglick could comment though he will likely push-bask the use-case.

From the contributions PoV, I will do my best to review and test the proposed pull request
