### ISSUE TITLE
Groovy script is executed on master although job is configured to be executed on slave 

### ISSUE THREAD

**Issue by Spamme1** [jenkinsci/envinject-plugin#116]
The title says already everything, maybe for the coders nothing new, for me was, after a couple of hours of work on a test environment to put together a working groovy script and copy it on the production server, a disappointed "ah ha"! Yes, because the groovy script needs to read some information from the source code, which is rightly checked out on the slave server, but the groovy script is executed on the master! A couple of hours plus some more time to understand why the groovy script wasn't finding the specified paths, all this time wasted! Is there a particular reason to execute the groovy script on the master and not on the slave? Otherwise I don't see the utility of this "feature".

**Comment by oleg-nenashev** [comment]
This is how the plugin has been designed by the original maintainer. If you need different behavior, please create an issue in Jenkins JIRA or vote for an existing one.

Created https://issues.jenkins-ci.org/browse/JENKINS-43864 for the documentation improvements
