### ISSUE TITLE
[QUESTION] Evaluate Variable on Config Page

### ISSUE THREAD

**Issue by JordanGS** [jenkinsci/envinject-plugin#117]
Hi, more of a question/clarification. I use your plugin in addition to one of mine. I create the following variable

`MY_PATH=C:\Users\JordanGS\Docs\FOLDER`

I access this value via `${MY_PATH}` in a text box. Then i have a drop down list below it that lists all the files under the path provided. My issue now is that it's not evaluating the `${MY_PATH}` envinj variable. Is there any way to evaluate either an EnvInj or System Environment variable during **JOB CONFIG** and **NOT** during the build? Thanks

**Comment by oleg-nenashev** [comment]
Sorry, I do not actively monitor GitHub issues.
Generally it is possible though the plugin API is mostly designed for Runs. If you need specific API to use it in your plugin during Job configuration, please raise a "New Feature" ticket in JIRA and describe the desired API there
