### ISSUE TITLE
Feature request: option for "prep environment for the run" to only fire on master in matrix builds

### ISSUE THREAD

**Issue by omehegan** [jenkinsci/envinject-plugin#22]
I've struggled for a very long time with a particular use case we have, which I cannot seem to accomplish elegantly in Jenkins using various plugins I have tried. I need to be able to run a shell script *once,* take some output from it and put that in an environment variable that is accessible to all build and post-build steps in matrix jobs.

I tried to do this with envinject, but when I use the 'Prepare an environment for the run' option and put my shell script in there, I am seeing that it gets run both on the master/parent and on all slaves in a matrix job, so this won't work for me. An option to restrict this to the parent would be ideal.

If someone wants to point me in the direction of implementing it myself, I would be happy to attempt it. I don't know much Java though.

**Comment by oleg-nenashev** [comment]
@omehegan Is it still actual? If yes,please create a JIRA ticket

**Comment by omehegan** [comment]
I found another plugin that provided this functionality (script to set job parameters only running on the master). It's obscure though, but now I'm moving all my builds to Pipeline which solves the problem for me. You can close this if you want.

**Comment by oleg-nenashev** [comment]
OK.
