### ISSUE TITLE
 Properties File Path handles ${VARIABLES} in filename inconsistently

### ISSUE THREAD

**Issue by andrewmacleod** [jenkinsci/envinject-plugin#23]
I want to load a properties file such as /opt/jenkins/${GIT_COMMIT}.properties.

If I define Properties File Path in "Prepare an environment for the run" then it is interpreted as a literal (which is unhelpful); however Properties File Path in "Inject environment variables" (i.e. as a build step) is interpreted correctly (i.e. the filename is dynamic).

Loading the properties file as a build step is a partial workaround, except that options such as "Load script and properties files from the master" are not presented at this stage.

It would be helpful if both "Properties File Path" fields interpreted variables in the filename.

**Comment by reubenavery** [comment]
Also frustrated by this, however I'm not using GIT_COMMIT but a parameter variable and it's no worky work :(

**Comment by Brantone** [comment]
+1
My scenario is following build steps:
1.) Export parameters to file ... thus making EXPORT_PARAMS_FILE available
2.) Execute shell ... appending params, using $EXPORT_PARAMS_FILE
3.) Inject environment variables > Properties File Path ... using $EXPORT_PARAMS_FILE, but throws error: The given properties file path '$EXPORT_PARAMS_FILE' doesn't exist.

**Comment by Brantone** [comment]
https://github.com/jenkinsci/envinject-plugin/blob/master/src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectEnvVars.java#L49 calls https://github.com/jenkinsci/envinject-plugin/blob/master/src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesVariablesRetriever.java#L27

Looks like not passing current info.

**Comment by oleg-nenashev** [comment]
Moved it to https://issues.jenkins-ci.org/browse/JENKINS-44977
