### ISSUE TITLE
EnvInject exposes password hashes

### ISSUE THREAD

**Issue by ggrieves** [jenkinsci/envinject-plugin#35]
This issue has been reported here https://issues.jenkins-ci.org/browse/JENKINS-24287
I just want to bring it to attention here since it is ongoing.

While viewing a build history, we can view all environment variables and saved as injectedEnvVars.txt
including passwords recorded as plaintext. 

We are using Jenkins 1.575
Envinject 1.89
Mask Passwords 2.7.2
and issue also happens with Parameterized Build password parameters, with either stored or nonstored types

**Comment by oleg-nenashev** [comment]
#57 added this functionality in 1.92
