### ISSUE TITLE
Feature Request: Read a property from value only file

### ISSUE THREAD

**Issue by efficks** [jenkinsci/envinject-plugin#44]
I have a file with the product version in it.
*version.txt*
> 1.0.0

I want to inject this value in a jenkins build. I can't change the file to follow a property file format.
I need a feature to be able to specify the property file has only 1 single value.

**Comment by oleg-nenashev** [comment]
env-inject provides extension points to implement this feature.
BTW, you could just use a script step to create a temporary file in *.properties format

**Comment by flberger-work** [comment]
I second the original request. It would be extremly convenient to have that possibility.

We currently invoke Python to creat a single-line temp file to be parsed by env-inject. One more failure point. We would love to skip that and use env-inject directly.

**Comment by daniel-beck** [comment]
Filed in Jira as [JENKINS-27895](https://issues.jenkins-ci.org/browse/JENKINS-27895).

I hate this second issue tracker.

**Comment by oleg-nenashev** [comment]
:+1: for disabling it at all as we do for other plugins.
BTW, only @jenkinsci/owners have permissions to do it.

**Comment by oleg-nenashev** [comment]
Closing this issue, because a bugtracker one exists
