### ISSUE TITLE
Jenkins pass all environment variables to a script

### ISSUE THREAD

**Issue by vasiliyb** [jenkinsci/envinject-plugin#48]
Folks,
  I am trying to plugin a custom python app into my Jenkins pipeline.  The app needs `ALL` of current `Environment Variables` to be passed in.  

I can either provide them in via cli, or write all of them to a file in the workspace.  How would you solve this?  

Is this a way out? https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin or https://wiki.jenkins-ci.org/display/JENKINS/SharedObjects+Plugin

Thanks!

PS  Linked from StackOverflow http://stackoverflow.com/questions/29922654/jenkins-pass-all-environment-variables-to-a-script

**Comment by vasiliyb** [comment]
Ideally, I would like the pipeline to keep updating a file, which i can then shoot over to a python app.  Based upon contents of this file, the app will do a multitude of things :)

Thanks!

**Comment by oleg-nenashev** [comment]
Please use jenkins-users Google mail list or IRC if you want to ask a question. GitHub issues are not being used by default in Jenkins community, I hope this feature will be disabled for this plugin as well.
