### ISSUE TITLE
Execute inline groovy script adds script content to build log

### ISSUE THREAD

**Issue by jamestelfer** [jenkinsci/envinject-plugin#52]
When executing an inline groovy script to get the environment map, the entire executed snippet is output into the build log.

IMO, this distracts from the information that I generally want to get from the build log, so I'd like this behaviour to be changed. However, I understand that this might be helpful for some to know what script is being executed.

I would like to change the plugin to accommodate this change, but I'd like to know what kind of solution would be acceptable.

As I see it, there are a few options:
1. Don't log the script at all, just log that the inline Groovy script is being executed.
2. Log the first line of the script
3. Log the first `n` characters of the script, followed by an ellipsis
4. Log the first comment line from the script.

Honestly, I think (1) is the better option, as I don't see much utility in logging the entire script. I'd welcome a response though, and I'll look to put a pull request together for the agreed fix.

**Comment by oleg-nenashev** [comment]
Please create an issue on Jenkins JIRA. This bugtracker is a a legacy one
