### ISSUE TITLE
Feature request: Select password from credentials

### ISSUE THREAD

**Issue by bartoszj** [jenkinsci/envinject-plugin#59]
Right now this plugins allows to inject *custom* name and password or *global* name and password. It would be nice to select username and password stored inside Credentials.

**Comment by oleg-nenashev** [comment]
Please submit an issue on Jenkins JIRA. This bugtracker is a rudiment

**Comment by bartoszj** [comment]
OK. Sorry for that.
This request duplicates task https://issues.jenkins-ci.org/browse/JENKINS-26547.
