### ISSUE TITLE
Use multiple properties files

### ISSUE THREAD

**Issue by mb720** [jenkinsci/envinject-plugin#75]
Hi and thank you for your great plugin!

I have split my project's configuration into multiple .properties files.
Is there a way for EnvInject to read all of these files and make the variables they contain available to my Jenkins build?

The first thing that came to my mind was to separate the files to be read with a semicolon like this:
![multiplefiles](https://cloud.githubusercontent.com/assets/4164548/10425608/30301bd0-70d9-11e5-8941-b1fd9b4934ab.PNG)

Thanks in advance!

**Comment by oleg-nenashev** [comment]
Currently there is no such option.
Related thread in jenkinsci-dev: https://groups.google.com/forum/#!searchin/jenkinsci-dev/EnvFile|sort:date/jenkinsci-dev/qaAQTgg7uJM/cAn_de8lCQAJ
