### ISSUE TITLE
Still seeing masked passwords with EnvInject 1.92.1, Jenkins 1.609

### ISSUE THREAD

**Issue by seanmckinley** [jenkinsci/envinject-plugin#76]
I'm not sure if I'm just misunderstanding something and doing something horribly wrong, or if I just have the wrong combination of plugins, but I'm seeing masked passwords in our environment variables (without checking the masked passwords box).

![screen shot 2015-10-23 at 3 14 17 pm](https://cloud.githubusercontent.com/assets/3581034/10706424/a79f2588-799b-11e5-87e8-d3a36e96f858.png)

When running the following 'execute shell' step in just a clean freestyle project, I see the following in the console output:

[durp] $ /bin/sh -xe /tmp/hudson2316170809764901844.sh
+ env
+ grep -i test_pass
test_pass=****

When reading through the changelog, it seems this was resolved, so I guess I'm kind of stumped. Any ideas?

**Comment by recena** [comment]
Why do not you use Jenkins JIRA?

**Comment by seanmckinley** [comment]
Guess I'm just a dummy. 

I moved the issue to Jenkins JIRA. Thanks recena.
