### ISSUE TITLE
Plugin Masking Path Variable

### ISSUE THREAD

**Issue by charleshamel73** [jenkinsci/envinject-plugin#85]
Hello,
I have set a global variable Path in my Global Master Properties(Manage Jenkins -> Configure System -> Global Properties) with the value $PATH;C:\Python27\Lib\site-packages\AutomationTools\scripts;C:\Python27\Lib\site-packages\AutomationTools\lib;$WORKSPACE.
When running a build I find that the environment variable Path in the build doesn't include the above values. Once I uninstall EnvInject, I noticed that the Path properly appends the value. How do I go about appending values to already defined environment variables from global properties without uninstalling envinject.

**Comment by charleshamel73** [comment]
Ignore Somehow restarting jenkins fixed it.

**Comment by marshall-prosperworks** [comment]
I am seeing this problem myself, and restarting Jenkins is not fixing it

**Comment by brenguy** [comment]
Please fix this. Running Jenkins 2.11 and envinj 1.92.1.

**Comment by oleg-nenashev** [comment]
Still actual. I'll find a proper JIRA issue and close this one

**Comment by ishug86** [comment]
Are there any updates to it ? I believe this plugin is also causing the same problem in our jenkins environment , where the slaves keeps loosing the path variable. I have raised this question here for more details : http://stackoverflow.com/questions/41113589/jenkins-jobs-on-slaves-keep-on-losing-the-path-environment-variables-values

**Comment by MrPrimate** [comment]
Same issue here.

**Comment by dgeissl** [comment]
Sounds much like https://issues.jenkins-ci.org/browse/JENKINS-26583

**Comment by oleg-nenashev** [comment]
Closing since there are duplicates. Let's proceed in the JIRA bugtracker, I am disabling GitHub issues for the plugin
