### ISSUE TITLE
Add ability to override log level for this plugin on a per job basis

### ISSUE THREAD

**Issue by keviny22** [jenkinsci/envinject-plugin#86]
In my jobs I want to suppress `info` level logging to the job console output. I would be great if there was a way to set this at the per job level.

**Comment by oleg-nenashev** [comment]
It is not something which can be done in java.util.logging.logger. A solution on the Jenkins side is possible, but the added value is not so high IMHO. Please create an issue in Jenkins JIRA for it if you still want to get such behavior
