### ISSUE TITLE
EnvInject plugin does not inject variables if job is triggered remotely

### ISSUE THREAD

**Issue by zeridon** [jenkinsci/envinject-plugin#88]
Simple job is attached to demonstrate the issue.

Basically:
 * I have a parametrized build that is executing shell script
 * I am prepping the build env with EnvInject (groovy script)
 * If a parametric var is not defined the groovy script is supposed to set it from another that is defined
 * This works if i trigger the build from the Jenkins web interface
 * This does not work if i trigger the job via the rest API (with token)

Versions:
 * Jenkins: 1.650
 * EnvInject: 1.92.1
 * OS: Linux
 * Setup: master + slaves
 * Override Build Parameters is set to true

[envinject-test-job.txt](https://github.com/jenkinsci/envinject-plugin/files/182374/envinject-test-job.txt)
[envinject-test-job-out.txt](https://github.com/jenkinsci/envinject-plugin/files/182378/envinject-test-job-out.txt)

**Comment by zeridon** [comment]
And now it even stopped working when triggering the job manually from the web interface.

**Comment by oleg-nenashev** [comment]
"parent.builds[0]" retrieves the variables for the first build. If it gets deleted, your script won't operate correctly anymore.

Cannot diagnose more without info about job and this build. If you're still affected by the issue, please create a Jenkins JIRA ticket. This bugtracker is deprecated.
