### ISSUE TITLE
Released Envinject Plugin is not up to date with master

### ISSUE THREAD

**Issue by paul-schwendenman** [jenkinsci/envinject-plugin#89]
A couple months ago, PR https://github.com/jenkinsci/envinject-plugin/pull/83 accepted to fix a bug. However the plugin has not been released since that. Is there a timeline for releasing this plugin?

**Comment by oleg-nenashev** [comment]
I'll do it once I upgrade the stuff to the new Parent POM. There are several issues with it

**Comment by paul-schwendenman** [comment]
Is this something I might be able to help with? Is it related to this PR https://github.com/jenkinsci/envinject-plugin/pull/82? 

If you could advise what you are trying to upgrade, I might be able help.

**Comment by oleg-nenashev** [comment]
Nope, I just need to find some time :(

**Comment by oleg-nenashev** [comment]
It has been upgraded in https://github.com/jenkinsci/envinject-plugin/pull/99/
Hope to release new EnvInject version tomorrow

**Comment by oleg-nenashev** [comment]
#100 Has been integrated, but the release is getting delayed
