### ISSUE TITLE
Weird behaviour while trying to inject variables "http_proxy", "no_proxy", etc

### ISSUE THREAD

**Issue by tallandtree** [jenkinsci/envinject-plugin#91]
Hello,

I try to use EnvInject to inject the variables: http_proxy, https_proxy, no_proxy into my build step.

I use **"Inject environment variables to the build process"/"Properties Content"** to define the variables. 
With the environment variables: http_proxy, https_proxy, no_proxy, this does not seem to work. But if I rename these environment variables to something like: xno_proxy or yhttp_proxy, I do see the correct output. Most strange thing is, when I use xhttp_proxy it is empty, but xhttpx_proxy or yhttp_proxy both "work" ok. 
Hope so
[config.xml.txt](https://github.com/jenkinsci/envinject-plugin/files/270192/config.xml.txt)

meone can explain what I'm doing wrong, because I can't figure it out.

See attached config.xml.txt for job specification details.
I've added one build step which executes a shell and echo's the variables.

**Console output:**
[EnvInject] - Executing scripts and injecting environment variables after the SCM step.
[EnvInject] - Injecting as environment variables the properties content 
xHTTP_PROXY="http://proxy:8080"
xHTTPS_PROXY="http://proxy:8080"
xhttps_proxy="http://proxy:8080"
xhttpsx_proxy="http://proxy:8080"
no_proxy=sys-registry1.mydom.com
xno_proxy=sys-registry1.mydom.com
yhttp_proxy="http://proxy:8080"
xhttp_proxy="http://proxy:8080"
http_proxy="http://proxy:8080"
``
[EnvInject] - Variables injected successfully.
[workspace] $ /bin/sh -xe /tmp/hudson1919548272544955726.sh
+ echo xno_proxy=sys-registry1.mydom.com
xno_proxy=sys-registry1.mydom.com
+ echo yhttp_proxy="http://proxy:8080"
yhttp_proxy="http://proxy:8080"
+ echo xhttp_proxy=
xhttp_proxy=
+ echo http_proxy="http://proxy:8080"
http_proxy="http://proxy:8080"
+ echo no_proxy=
no_proxy=

Jenkins version: 1.642.3
EnvInject version: 1.92.1

**Comment by oleg-nenashev** [comment]
Still needs to be analyzed

**Comment by oleg-nenashev** [comment]
Moved it to https://issues.jenkins-ci.org/browse/JENKINS-44976
