### ISSUE TITLE
EnvInject doesnt evaluate the variable

### ISSUE THREAD

**Issue by mihok** [jenkinsci/envinject-plugin#93]
It's not possible to evaluate a variable on assignment. Using the '`' tick character as you may do in a bash script which executes commands and the return of those commands becomes the variable.

**Comment by oleg-nenashev** [comment]
I doubt such feature is going to happen, because it requires support of arbitrary interpreters, not only bash. You can always generate property file in Script build step and then to inject this file as a workaround.

If you disagree && want to implement this feature, please create a JIRA issue
