### ISSUE TITLE
EnvInject doesn't seem to support Scripter scripts

### ISSUE THREAD

**Issue by agray** [jenkinsci/envinject-plugin#94]
I can enter the content of a Groovy script (via Evaluated Groovy script field). 

it would greatly improve management to be able to put this content in a groovy file or scripter script and be able to source the groovy script content from that one central place when configuring the EnvInject plugin in a job.

**Comment by oleg-nenashev** [comment]
It does not. EnvInject script engine is a subject for the full rework, so maybe it changes at some point

**Comment by agray** [comment]
Thanks @oleg-nenashev.  Is there any planned roadmap for when envinject will support scriptler?

**Comment by oleg-nenashev** [comment]
@agray No short-term plans. If somebody creates a pull request, I'll try to review it. If I start working on the plugin soon, I'll probably provide proper extension points allowing to specify different script sources.

**Comment by oleg-nenashev** [comment]
Please create an RFE on Jenkins JIRA for this case

**Comment by agray** [comment]
Please excuse my stupid question:

What does RFE stand for?

Request For...? And how do I create one of them?

**Comment by oleg-nenashev** [comment]
Sorry for that unclear response. I meant that it makes sense to create a "New feature" request in Jenkins JIRA (it's a special issue type). See https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue
