### ISSUE TITLE
EnvInject-Plugin: Inject Variables not getting resolved in powershell nor Windows Batch script

### ISSUE THREAD

**Issue by esramirez** [jenkinsci/envinject-plugin#98]
My problem is that the an injected variable is not getting resolved when use within script build step. 

Plugin Version: 1.3
Jenkins Version: 1.620
Build Pipeline plugin: 1.5.3.1 

smokedBuild.log contents:
BUILD_UNDER_TEST=Drivers  (2016-07-21 10-56-27 AM)

The powershell script:

Write-Host "According to the build log, the value for the smoked build is: $env:BUILD_UNDER_TEST"

The job's output is follow:
14:29:34 [EnvInject] - Injecting environment variables from a build step.
14:29:34 [EnvInject] - Injecting as environment variables the properties file path 'smokedBuild.log'
14:29:34 [EnvInject] - Variables injected successfully.
14:29:35 According to the build log, the value for the smoked build is:

**Comment by oleg-nenashev** [comment]
Maybe it's a Powershell specifics. Which plugin do you use?
For Batch cannot reproduce the issue. Everything works fine on my instance

**Comment by oleg-nenashev** [comment]
If the issue is still actually, please create a bug on Jenkins JIRA.
This bugtracker is deprecated
